### ISSUE TITLE
Odom topic have no output

### ISSUE THREAD

**Issue by HazemAbidi** [AlexKaravaev/ros2_laser_scan_matcher#1]
Hello,
I'm working on a project in Ros2 foxy and I want to use the laser scan matcher to get the odometry from it.
I changed publish_odom param to "odom" and publish_tf to true and I still don't have an output when I run `ros2 topic echo /odom` . Also the tf tree has no odom frame on it.
My diff drive plugin is the following:
`<gazebo>
    <plugin filename="libgazebo_ros_joint_state_publisher.so" name="joint_states">`
`  <gazebo>
    <plugin filename="libgazebo_ros_joint_state_publisher.so" name="joint_states">

      <joint_name>chassis_roue_motrice_droite</joint_name>
      <joint_name>chassis_roue_motrice_gauche</joint_name>
    </plugin>

    <plugin filename="libgazebo_ros_diff_drive.so" name="differential_drive_controller">
      <ros>
        
        <namespace></namespace>
        
        <remapping>/cmd_vel:=cmd_vel</remapping>
        
      </ros>
      
      <alwaysOn>true</alwaysOn>
      <legacyMode>false</legacyMode>
      <update_rate>100</update_rate>
      <left_joint>chassis_roue_motrice_gauche</left_joint>
      <right_joint>chassis_roue_motrice_droite</right_joint>
      <wheel_separation>0.6855600</wheel_separation>
      <wheel_diameter>0.2032000</wheel_diameter>
      <odometry_frame>odom</odometry_frame>
      
      <robot_base_frame>base_link</robot_base_frame>

      
      <max_wheel_torque>20</max_wheel_torque>
      
      <publish_odom>false</publish_odom>
      <publish_odom_tf>false</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      
      <odometry_source>world</odometry_source>
      
    </plugin>
  </gazebo>`
After spawning the robot I just run the laser_scan_matcher executable file.
Any idea please.
I thank you in advance

**Comment by AlexKaravaev** [comment]
Have you checked rqt_graph, to check whether laser_scan_matcher subscribed to correct topic of laser scan?

**Comment by HazemAbidi** [comment]
Yes I did that it appears that the laser_scan_matcher subscribe to the /scan topic but it didn't subscribe to the /tf topic. Also it publishes only /tf and there is no odom frame in the tf tree.

**Comment by AlexKaravaev** [comment]
I don't understand, node is publishing /tf and /odom topics or not? 
>  Also, it publishes /tf and /odom topics.

I have checked now, it should publish both, if parameters are set correctly. 

Can you please check following things:
1) Parameters are actually set. Better to do that with `ros2 param get ...`
2) Node is actually launched and running

Also, it would be helpful if you post console output here when you launch the node.

**Comment by HazemAbidi** [comment]
Hello,
Alright this is my rqt graph :
![rqt_graph_lsm](https://user-images.githubusercontent.com/58831775/112199800-d40d3c00-8c0e-11eb-8449-8a71440a453f.png)
So these are the params that I've changed: 
`  add_parameter("publish_odom", rclcpp::ParameterValue(std::string("odom")),
    "If publish odometry from laser_scan. Empty if not, otherwise name of the topic");
  add_parameter("publish_tf",   rclcpp::ParameterValue(true),
    " If publish tf odom->base_link");`
And finally the console:
![lsm_console](https://user-images.githubusercontent.com/58831775/112200435-847b4000-8c0f-11eb-9654-e614705f04e8.png)
for the params : 
![lsm_console](https://user-images.githubusercontent.com/58831775/112200908-00758800-8c10-11eb-8e28-dac27e2f8b92.png)

**Comment by AlexKaravaev** [comment]
Thank you for the output, all looks fine for me. Due to the fact, that when you echo topic it says nothing, it maybe unmatched QoS settings. If the topic is not published it should say ```WARNING: topic [/odom] does not appear to be published yet```. 

Can you double check in rviz, that odom is not published?

**Comment by HazemAbidi** [comment]
Thank you for your quick response.
I checked Rviz as I said I haven't found an odometry frame.
I changed the durability and reliability policies of the Odom topic and nothing happened. (tried transient local durability and best-effort reliability)
Isn't meant that laser scan matcher node to subscribe to /tf topic.
Because it doesn't appear that it is subscribing to it in the rqt_graph.
correct if I'm wrong please.

**Comment by AlexKaravaev** [comment]
Do you have any MWE? I've run all the latest files in simulation today and all worked fine. 

Also, you can double check that data arrives to the /scan topic. If you are using not the latest gazebo_ros_pkgs , it does use QoS by default, that will be unmatched by laser scanner (see this [PR](https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1235))

If there is no data on the /scan topic, please update gazebo_ros_pkgs to latest version, it should fix all the issues. Otherwise, you can send your package here and I will see what's the issue, because on my machine all is working.

**Comment by HazemAbidi** [comment]
Hey again, I checked the QoS of both publisher and subscriber of /scan topic.
![QoS](https://user-images.githubusercontent.com/58831775/112492659-bca29000-8d81-11eb-9f35-bfdc08f30d35.png)
As you can see the QoS is not compatible, gazebo_head_hoyoku is giving a best effort reliability however laser_scan_matcher wats a reliable reliability
This is the version of gazebo ros pkgs that I have and it says that it is the latest version
![gazebo_ros_pkgs](https://user-images.githubusercontent.com/58831775/112496833-5b7cbb80-8d85-11eb-84fe-95bb8d45be01.png)

**Comment by AlexKaravaev** [comment]
I suggest you to build them from source, that way you guaranteed to get the latest version, but this issue is out of scope of this project, so I will close it
