### ISSUE TITLE
Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist.

### ISSUE THREAD

**Issue by cviper13** [AlexKaravaev/ros2_laser_scan_matcher#13]
`[INFO] [1709119247.248822323] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. `

I'm using ros2-humble and its my first ros project also with ld19 lidar it would be nice if how can i fix more clearly.

full console:
`tulpariha@tulpariha:~/ros2_laser_scan_matcher/src$ ros2 run ros2_laser_scan_matcher laser_scan_matcher --ros-args --remap laser_scan_topic:=scan
[INFO] [1709119237.087324957] [laser_scan_matcher]: Creating laser_scan_matcher
[INFO] [1709119247.248822323] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119247.249182280] [laser_scan_matcher]: Skipping scan
[INFO] [1709119247.248822323] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist.[INFO] [1709119257.253388562] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119257.254226308] [laser_scan_matcher]: Skipping scan
[INFO] [1709119267.255765758] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119267.256759964] [laser_scan_matcher]: Skipping scan
[INFO] [1709119277.262842033] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119277.264045459] [laser_scan_matcher]: Skipping scan
[INFO] [1709119287.274912887] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119287.275161902] [laser_scan_matcher]: Skipping scan
[INFO] [1709119297.279194320] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119297.279587332] [laser_scan_matcher]: Skipping scan
[INFO] [1709119307.291363223] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119307.291612997] [laser_scan_matcher]: Skipping scan
[INFO] [1709119317.296614387] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119317.297458596] [laser_scan_matcher]: Skipping scan
[INFO] [1709119327.301661749] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119327.302632771] [laser_scan_matcher]: Skipping scan
[INFO] [1709119337.311693716] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119337.312284059] [laser_scan_matcher]: Skipping scan
[INFO] [1709119347.320518332] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119347.321590389] [laser_scan_matcher]: Skipping scan
^C[INFO] [1709119349.477907136] [rclcpp]: signal_handler(signum=2)
[INFO] [1709119349.494172234] [laser_scan_matcher]: Could not get initial transform from base to laser frame, "laser" passed to lookupTransform argument source_frame does not exist. 
[WARN] [1709119349.494320084] [laser_scan_matcher]: Skipping scan`

**Comment by jagauthier** [comment]
You need to set up a transform between the base and the laser.
Something like 
`run tf2_ros static_transform_publisher --x 0 --y 0 --z 0 --roll 0 --pitch 0 --yaw 0 --frame-id base_link --child-frame-id laser`

**Comment by cviper13** [comment]
late response, but worked thank!
